from typing import Optional
from pydantic import BaseModel, Field


class ChatRequest(BaseModel):
    message: str = Field(
        ...,
        description="The message or question for your personal assistant",
        examples=["What are my top priorities today?"]
    )


class ChatResponse(BaseModel):
    reply: str = Field(
        ...,
        description="The response generated by the local Qwen model"
    )
    model: str = Field(
        ...,
        description="The model name that produced the output"
    )
    total_duration_seconds: Optional[float] = Field(
        default=None,
        description="Total duration for the response generation in seconds"
    )
