from typing import Optional
from pydantic import BaseModel, Field


class ChatRequest(BaseModel):
    message: str = Field(
        ...,
        description="The message or question for your personal assistant",
        examples=["What are my top priorities today?"]
    )
    stream: bool = Field(
        default=True,
        description="Stream tokens in real-time via Server-Sent Events (SSE). Set to False for a single JSON response."
    )


class ChatResponse(BaseModel):
    reply: str = Field(
        ...,
        description="The complete answer response generated by the local Qwen model"
    )
    thinking: Optional[str] = Field(
        default=None,
        description="The step-by-step reasoning thought process (if generated by the model)"
    )
    model: str = Field(
        ...,
        description="The model name that produced the output"
    )
    total_duration_seconds: Optional[float] = Field(
        default=None,
        description="Total duration for the response generation in seconds"
    )
